version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - db_data:/var/lib/mysql

  api:
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - 3000:3000
    depends_on:
      - db
    environment: 
      DB_HOST: db
      DB_USERNAME: root
      DB_PASSWORD: 123456
      DB_DATABASE: juntai_development
      DB_PORT: 3306
      NODE_ENV: development
    command: npm run start:dev

volumes:
  db_data:
